# Generated by Django 3.2 on 2021-04-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_rename_loglist_blocklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blocklist',
        ),
    ]
